In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.3'

## Create & Read

## 1D Array

In [3]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [6]:
a1.ndim

1

In [7]:
a1.size

3

In [8]:
a1.shape

(3,)

## 2D Array

In [10]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a2.size

6

In [12]:
a2.ndim

2

In [13]:
a2.shape

(2, 3)

## 3D Array

In [18]:
a3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [19]:
a3.shape

(2, 2, 3)

In [20]:
a3.ndim

3

In [21]:
a3.size

12

## Random

In [27]:
R=np.random.rand(2,3,3)
R

array([[[0.99710901, 0.05109031, 0.05763599],
        [0.4278391 , 0.91592782, 0.66947365],
        [0.82536951, 0.51605955, 0.3097897 ]],

       [[0.62758849, 0.06560544, 0.12220927],
        [0.70476494, 0.16400881, 0.97596553],
        [0.99710367, 0.74795727, 0.83322817]]])

## Zeros

In [28]:
zeros=np.zeros([2,3,4])
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Ones

In [29]:
ones=np.ones([2,2,2])
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

## Full

In [30]:
f=np.full([2,2,2],8)
f

array([[[8, 8],
        [8, 8]],

       [[8, 8],
        [8, 8]]])

## Accessing

In [33]:
R

array([[[0.99710901, 0.05109031, 0.05763599],
        [0.4278391 , 0.91592782, 0.66947365],
        [0.82536951, 0.51605955, 0.3097897 ]],

       [[0.62758849, 0.06560544, 0.12220927],
        [0.70476494, 0.16400881, 0.97596553],
        [0.99710367, 0.74795727, 0.83322817]]])

In [39]:
R[0,1,1]

np.float64(0.9159278163585153)

In [40]:
R[0:1]

array([[[0.99710901, 0.05109031, 0.05763599],
        [0.4278391 , 0.91592782, 0.66947365],
        [0.82536951, 0.51605955, 0.3097897 ]]])

## Update & Delete

In [42]:
a1=np.random.rand(2,2,2)
a1

array([[[0.43788305, 0.17551471],
        [0.55167106, 0.02876976]],

       [[0.34593079, 0.2053627 ],
        [0.49573356, 0.24087334]]])

In [43]:
a2=np.random.rand(2,2,2)
a2

array([[[0.89296011, 0.80562268],
        [0.68668428, 0.19195753]],

       [[0.07646472, 0.3146686 ],
        [0.22972985, 0.03838357]]])

In [44]:
np.add(a1,a2)

array([[[1.33084316, 0.98113738],
        [1.23835534, 0.22072728]],

       [[0.42239551, 0.5200313 ],
        [0.72546341, 0.27925691]]])

In [46]:
np.subtract(a1,a2)

array([[[-0.45507705, -0.63010797],
        [-0.13501322, -0.16318777]],

       [[ 0.26946606, -0.1093059 ],
        [ 0.26600371,  0.20248977]]])

## Statistical Operation

In [47]:
np.sqrt(25)

np.float64(5.0)

In [49]:
np.square(5)

np.int64(25)

In [50]:
np.abs(-2)

np.int64(2)

In [51]:
np.power(2,8)

np.int64(256)

In [52]:
np.log(2)

np.float64(0.6931471805599453)

In [53]:
np.max(a1)

np.float64(0.5516710643045427)

In [54]:
np.min(a2)

np.float64(0.03838357069633502)

## Update 

In [60]:
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [65]:
a3[1,0,1]=634
a3

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  1, 634,   3],
        [  4,   5,   6]]])

In [67]:
a3.sort()
a3

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  1,   3, 634],
        [  4,   5,   6]]])

## Reshape
Make sure whatever dimension you pass should be able to accomodate all the elements

In [70]:
a3.reshape(2,1,6) 

array([[[  1,   2,   3,   4,   5,   6]],

       [[  1,   3, 634,   4,   5,   6]]])

In [72]:
a3.reshape(2,1,-1) # If you are not sure about last dimension then you can give -1, it'll handle it automatically

array([[[  1,   2,   3,   4,   5,   6]],

       [[  1,   3, 634,   4,   5,   6]]])

## Appending & Inserting

In [73]:
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [83]:
new_array=np.ones((2,3,4))
new_array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [84]:
appd=np.append(zeros, new_array, axis=0)  # Here we are appending new_array to zeros
appd

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [85]:
insert=np.insert(zeros, 1, new_array, axis=0)
insert

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Delete

In [ ]:
np.delete(insert, 0, axis=1)
